# Generated by Django 3.2.4 on 2022-12-02 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='post/')),
                ('file_preview', models.ImageField(null=True, upload_to='post/')),
                ('duration', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fileuploadpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='post/')),
                ('file_preview', models.ImageField(null=True, upload_to='post/')),
                ('duration', models.FloatField(default=0)),
                ('tags', models.TextField(null=True)),
                ('note', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(max_length=1500)),
                ('posted', models.DateTimeField(auto_now=True)),
                ('emotion', models.CharField(max_length=100, null=True)),
                ('comment', models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Private'), ('5', 'Specific friends'), ('6', 'Custom'), ('7', 'Best friend'), ('8', 'Unnamed list'), ('9', 'Acquaintance')], default='1', max_length=100)),
                ('viewer', models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Private'), ('5', 'Specific friends'), ('6', 'Custom'), ('7', 'Best friend'), ('8', 'Unnamed list'), ('9', 'Acquaintance')], default='1', max_length=100)),
                ('gim', models.BooleanField(default=False)),
                ('accept_viewer', models.ManyToManyField(blank=True, related_name='accept_viewer_post', to=settings.AUTH_USER_MODEL)),
                ('commenters', models.ManyToManyField(blank=True, related_name='accept_commenters', to=settings.AUTH_USER_MODEL)),
                ('exception_viewer', models.ManyToManyField(blank=True, related_name='exception_viewer_post', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_group', to='groups.group')),
                ('hide_post', models.ManyToManyField(blank=True, related_name='hide_post', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='tags_post', to=settings.AUTH_USER_MODEL)),
                ('turn_off_notifications', models.ManyToManyField(blank=True, related_name='turn_off_notifications', to=settings.AUTH_USER_MODEL)),
                ('turn_on_notifications', models.ManyToManyField(blank=True, related_name='turn_on_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True)),
                ('caption', models.TextField(max_length=1500, null=True)),
                ('viewer', models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Private'), ('5', 'Specific friends'), ('6', 'Custom'), ('7', 'Best friend'), ('8', 'Unnamed list'), ('9', 'Acquaintance')], default='Public', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exception_viewer', models.ManyToManyField(blank=True, related_name='exception_viewer_story', to=settings.AUTH_USER_MODEL)),
                ('fileupload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='post.fileupload')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags_story', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Story_emotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_emoji', models.TextField(default='', max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='post.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sharepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=50, null=True)),
                ('viewer', models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Private'), ('5', 'Specific friends'), ('6', 'Custom'), ('7', 'Best friend'), ('8', 'Unnamed list'), ('9', 'Acquaintance')], default='4', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accept_viewer', models.ManyToManyField(blank=True, related_name='accept_viewer_save', to=settings.AUTH_USER_MODEL)),
                ('posts', models.ManyToManyField(blank=True, related_name='post_save', to='post.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reportstory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reportpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reportfilepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('filepost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.fileuploadpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_emotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('like', 'like'), ('love', 'love'), ('wow', 'wow'), ('sad', 'sad'), ('smile', 'smile'), ('indignant', 'indignant')], max_length=10)),
                ('created', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Hideuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hide_user', models.ManyToManyField(blank=True, related_name='hide_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fileuploadpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_post', to='post.post'),
        ),
        migrations.AddField(
            model_name='fileuploadpost',
            name='turn_off_file',
            field=models.ManyToManyField(blank=True, related_name='turn_off_file', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileuploadpost',
            name='turn_on_file',
            field=models.ManyToManyField(blank=True, related_name='turn_on_file', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileuploadpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Filepost_emotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('like', 'like'), ('love', 'love'), ('wow', 'wow'), ('sad', 'sad'), ('smile', 'smile'), ('indignant', 'indignant')], max_length=10)),
                ('created', models.DateTimeField(auto_now=True)),
                ('filepost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filepost', to='post.fileuploadpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
