# Generated by Django 3.2.4 on 2022-12-02 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('story', models.TextField(blank=True, max_length=100, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('hobby', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('online', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('is_online', models.DateTimeField(auto_now=True, null=True)),
                ('coins', models.IntegerField(default=0)),
                ('count_notify_unseen', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField(null=True)),
                ('cover_image', models.ImageField(null=True, upload_to='profile/')),
                ('gender', models.CharField(choices=[('1', 'MALE'), ('2', 'FEMALE'), ('3', 'ORTHER')], max_length=10, null=True)),
                ('avatar', models.ImageField(default='profile/userno_gwinne.png', null=True, upload_to='profile/')),
                ('blocked_users', models.ManyToManyField(blank=True, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('friend_invitation', models.ManyToManyField(blank=True, related_name='friend_invitation', to=settings.AUTH_USER_MODEL)),
                ('hide_post_user', models.ManyToManyField(blank=True, related_name='hide_post_user', to=settings.AUTH_USER_MODEL)),
                ('hide_story_user', models.ManyToManyField(blank=True, related_name='hide_story_user', to=settings.AUTH_USER_MODEL)),
                ('hide_suggested', models.ManyToManyField(blank=True, related_name='hide_suggested', to=settings.AUTH_USER_MODEL)),
                ('likers', models.ManyToManyField(blank=True, related_name='likers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SMSVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verifyemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(max_length=200)),
                ('position', models.TextField(max_length=200, null=True)),
                ('description', models.TextField(max_length=1500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('viewer', models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Specific friends'), ('5', 'Private')], default='Public', max_length=100)),
                ('exception_viewer', models.ManyToManyField(blank=True, related_name='exception_viewer_workplace', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('from_time', models.DateField(null=True)),
                ('to_time', models.DateField(null=True)),
                ('granduated', models.BooleanField(default=True)),
                ('specialized', models.TextField(max_length=1500, null=True)),
                ('degree', models.TextField(max_length=1500, null=True)),
                ('description', models.TextField(max_length=1500, null=True)),
                ('viewer', models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Specific friends'), ('5', 'Private')], default='Public', max_length=100)),
                ('exception_viewer', models.ManyToManyField(blank=True, related_name='exception_viewer_university', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('viewer', models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Specific friends'), ('5', 'Private')], default='Public', max_length=100)),
                ('exception_viewer', models.ManyToManyField(blank=True, related_name='exception_viewer_relationship', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Highschool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('from_time', models.DateField(null=True)),
                ('to_time', models.DateField(null=True)),
                ('granduated', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=1500, null=True)),
                ('viewer', models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Specific friends'), ('5', 'Private')], default='Public', max_length=100)),
                ('exception_viewer', models.ManyToManyField(blank=True, related_name='exception_viewer_highschool', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('habitat_type', models.CharField(choices=[('1', 'Hometown'), ('2', 'Current city'), ('3', 'City')], max_length=100)),
                ('from_time', models.DateField(null=True)),
                ('to_time', models.DateField(null=True)),
                ('viewer', models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Specific friends'), ('5', 'Private')], default='Public', max_length=100)),
                ('exception_viewer', models.ManyToManyField(blank=True, related_name='exception_viewer_habitat', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_friend', models.BooleanField(default=False)),
                ('acquaintance', models.BooleanField(default=False)),
                ('restricted', models.BooleanField(default=False)),
                ('unnamed_list', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to='accounts.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
