# Generated by Django 3.2.4 on 2022-12-02 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchcurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(max_length=90, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_serach', to=settings.AUTH_USER_MODEL)),
                ('user_search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resut_seach', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_preview', models.FileField(null=True, upload_to='post/')),
                ('accept', models.BooleanField(default=False)),
                ('notification_type', models.IntegerField(choices=[(1, 'Emotions'), (2, 'Comment'), (3, 'Follow'), (5, 'Addfriend'), (7, 'Accept friend request'), (4, 'Mentions'), (6, 'Post')])),
                ('text_preview', models.TextField(blank=True, max_length=90)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.comment')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
